### ISSUE TITLE
How to use options provided in GAE defer e.g. _transactional, _retry_options in this library?

### ISSUE THREAD

**Issue by hamidarrivy** [freshplanet/AppEngine-Deferred#4]
I am trying to use this library in my project. But, looking at the code of "tasks.py" i just realized that options like "_transactional", "_retry_options" etc can not be used in this library. However, they are present in original GAE deferred library and are quite useful. 
Any plan of providing support of these options?

**Comment by hamidarrivy** [comment]
I have requested a Pull request with the respective changes to support "_transactional" and "_retry_options ". Please accept it and close this issue.
Thanks!

**Comment by AlexisH** [comment]
Indeed these were missing. Thank you !
